package com.cliftonia.fs42tv.resolver

/**
 * Choosing an English subtitle track from what a clip offers.
 *
 * Measured across sixteen clips on the Martial Arts and Anime channels, which are the two that
 * genuinely need this: fourteen had English captions available, but only four of those were
 * hand-authored. The other ten had nothing but YouTube's automatic transcription.
 *
 * So automatic captions are NOT treated as second best to be used only in desperation. A feature
 * that accepted hand-authored subtitles alone would work on a quarter of the content and read as
 * broken; imperfect subtitles on a dubbed film nobody can otherwise follow beat no subtitles by
 * a wide margin. Manual is preferred where it exists, and automatic is a first-class fallback.
 *
 * Pure so the choice can be tested. Which track gets picked is invisible until someone turns
 * captions on in front of a television, and by then the wrong answer looks like a broken feature
 * rather than a wrong preference.
 */
object Captions {

    /** One subtitle track, reduced to what choosing between them actually needs. */
    data class Track(
        val url: String,
        val languageTag: String,
        val autoGenerated: Boolean,
        val format: String?,
    )

    /**
     * The best English track, or null when there is none worth showing.
     *
     * Formats are filtered rather than converted: both engines read WebVTT, and handing mpv or
     * Media3 a format it cannot parse produces a clip that plays with no captions and no error,
     * which is indistinguishable from a clip that simply had none.
     */
    fun pick(tracks: List<Track>): Track? =
        tracks
            .filter { it.url.isNotBlank() }
            .filter { isEnglish(it.languageTag) }
            .filter { readable(it.format) }
            // Manual first, then by tag so the choice is stable rather than dependent on the
            // order the extractor happened to return. An unstable pick would make a bug here
            // reproduce only sometimes, which is the hardest kind to chase.
            .minWithOrNull(
                compareBy<Track> { if (it.autoGenerated) 1 else 0 }.thenBy { it.languageTag }
            )

    /**
     * Whether a tag names English.
     *
     * Prefix matching, because YouTube writes regional variants: en, en-US, en-GB, en-orig, and
     * `a.en` for some automatic tracks. Exact matching on "en" would reject nearly all of them.
     */
    fun isEnglish(tag: String?): Boolean {
        val lowered = tag.orEmpty().lowercase()
        return lowered == "en" || lowered.startsWith("en-") || lowered.startsWith("en.") ||
            lowered.endsWith(".en") || lowered.startsWith("en_")
    }

    /** Formats both engines can parse. Anything else would show nothing and say nothing. */
    fun readable(format: String?): Boolean =
        format?.lowercase() in setOf("vtt", "webvtt", "srt", "ttml", null)
}
