package com.cliftonia.fs42tv.resolver

import org.junit.Ignore
import org.junit.Test
import org.schabi.newpipe.extractor.NewPipe
import org.schabi.newpipe.extractor.ServiceList
import org.schabi.newpipe.extractor.localization.ContentCountry
import org.schabi.newpipe.extractor.localization.Localization
import org.schabi.newpipe.extractor.stream.StreamInfo

/**
 * What subtitle tracks a clip actually offers, and whether [Captions] would take one.
 *
 * Written because captions were switched on in front of a television and nothing appeared, and
 * there are five separate places that could be true of: the track list is empty, the url field is
 * not a url, the format is one this rejects, the language tag is spelled differently than
 * expected, or the player is being handed it correctly and ignoring it. This distinguishes the
 * first four from the fifth without needing the device at all.
 */
@Ignore("hits the live network; run by hand when captions do not appear")
class CaptionProbe {

    private val ids = listOf(
        "J5ApHjWevKg" to "Martial Arts, 36 tracks",
    )

    @Test
    fun `list every subtitle track and say what would be picked`() {
        NewPipe.init(NewPipeDownloader(), Localization("en", "AU"), ContentCountry("AU"))
        for ((id, label) in ids) {
            println("\n== $label ($id)")
            val info = runCatching {
                StreamInfo.getInfo(ServiceList.YouTube, "https://www.youtube.com/watch?v=$id")
            }.getOrElse { println("   extraction failed: $it"); continue }

            val subs = info.subtitles.orEmpty()
            println("   tracks: ${subs.size}")
            for (s in subs) {
                println("     tag=%-10s auto=%-5s fmt=%-6s url=%s".format(
                    s.languageTag, s.isAutoGenerated, s.format?.suffix,
                    s.content?.take(58) ?: "NULL"))
            }
            val tracks = subs.map {
                Captions.Track(it.content.orEmpty(), it.languageTag.orEmpty(),
                               it.isAutoGenerated, it.format?.suffix)
            }
            val picked = Captions.pick(tracks)
            println("   FULLURL ${picked?.url}")
            if (picked == null) { println("   picked: NOTHING"); continue }
            // Fetch it, and fetch it again asking for WebVTT, because what the player can read
            // matters more than what the extractor happened to hand back.
            for ((what, url) in listOf("as returned" to picked.url,
                                       "fmt=vtt" to picked.url + "&fmt=vtt")) {
                val head = runCatching {
                    java.net.URL(url).openStream().bufferedReader().use { it.readText() }
                }.map { it.trim().take(70).replace("\n", " ") }.getOrElse { "FAILED $it" }
                println("   %-12s %s".format(what, head.ifEmpty { "(empty body)" }))
            }
        }
    }
}
