package com.cliftonia.fs42tv.resolver

import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Which subtitle track gets shown.
 *
 * The choice is invisible until somebody turns captions on in front of a television, and by then
 * a wrong pick looks like a broken feature rather than a wrong preference - so it is decided here
 * where it can be seen.
 */
class CaptionsTest {

    private fun track(tag: String, auto: Boolean = false, format: String? = "vtt",
                      url: String = "https://s/$tag") =
        Captions.Track(url, tag, auto, format)

    @Test
    fun `a hand-authored track beats an automatic one`() {
        val got = Captions.pick(listOf(track("en", auto = true), track("en-US")))
        assertEquals("en-US", got?.languageTag)
        assertFalse(got!!.autoGenerated)
    }

    @Test
    fun `an automatic track is used when it is all there is`() {
        // Measured: ten of the fourteen clips with English captions had nothing else. Refusing
        // these would make the feature look broken on most of the content that needs it.
        val got = Captions.pick(listOf(track("de"), track("en", auto = true)))
        assertEquals("en", got?.languageTag)
        assertTrue(got!!.autoGenerated)
    }

    @Test
    fun `another language is never shown, however good the track`() {
        assertNull(Captions.pick(listOf(track("de"), track("es"), track("ja"))))
    }

    @Test
    fun `regional and automatic tags all count as english`() {
        // YouTube writes these several ways and exact matching on "en" rejects nearly all of them.
        for (tag in listOf("en", "en-US", "en-GB", "en-orig", "a.en", "en.overlapping")) {
            assertTrue(tag, Captions.isEnglish(tag))
        }
        for (tag in listOf("de", "es-419", "ja", "", null)) {
            assertFalse(tag ?: "null", Captions.isEnglish(tag))
        }
    }

    @Test
    fun `a format neither engine reads is refused rather than shown blank`() {
        // Handing an unreadable format to a player produces a clip with no captions and no
        // error, which cannot be told apart from a clip that had none to begin with.
        assertNull(Captions.pick(listOf(track("en", format = "srv3"))))
        assertNull(Captions.pick(listOf(track("en", format = "json3"))))
        assertEquals("en", Captions.pick(listOf(track("en", format = "vtt")))?.languageTag)
    }

    @Test
    fun `a track with no url is not a track`() {
        assertNull(Captions.pick(listOf(track("en", url = ""))))
    }

    @Test
    fun `nothing offered means nothing shown`() {
        assertNull(Captions.pick(emptyList()))
    }

    @Test
    fun `the choice is stable when two tracks are equally good`() {
        // An unstable pick makes a bug here reproduce only sometimes, which is the hardest kind
        // to chase on a television.
        val tracks = listOf(track("en-GB"), track("en-US"), track("en"))
        assertEquals(Captions.pick(tracks), Captions.pick(tracks.reversed()))
    }

    @Test
    fun `the track is asked for as webvtt, because ttml plays nowhere`() {
        // NewPipeExtractor builds these urls with fmt=ttml, which mpv cannot read at all and
        // which Media3 was being handed while labelled WebVTT. Captions were broken twice over
        // and silently both times.
        val got = Captions.pick(listOf(track("en",
            url = "https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=ttml")))
        assertEquals("https://www.youtube.com/api/timedtext?v=abc&lang=en&fmt=vtt", got?.url)
    }

    @Test
    fun `the format is replaced, never appended`() {
        // A second fmt parameter is ignored by the endpoint, which is exactly what made the first
        // attempt at this look as though vtt was unsupported.
        val out = Captions.asWebVtt("https://www.youtube.com/api/timedtext?v=a&fmt=ttml&x=1")
        assertEquals(1, Regex("fmt=").findAll(out).count())
        assertTrue(out.contains("fmt=vtt"))
        assertTrue("other parameters must survive", out.contains("x=1"))
    }

    @Test
    fun `a timedtext url with no format is given one`() {
        assertTrue(Captions.asWebVtt("https://www.youtube.com/api/timedtext?v=a")
            .endsWith("fmt=vtt"))
    }

    @Test
    fun `a url that is not youtube timedtext is left alone`() {
        // A hand-authored track hosted elsewhere is already whatever format it is, and rewriting
        // a parameter it never had would break the url.
        val other = "https://example.com/subs/en.vtt"
        assertEquals(other, Captions.asWebVtt(other))
    }
}
